apiVersion: v1
kind: ConfigMap
metadata:
  name: adventureshops-configmap
  namespace: dev
data:
  application2.yaml: |+
    spring:
      application:
        name: adventureshops
      servlet:
        context-path: /api/v1/
      datasource:
        url: jdbc:mysql://host.minikube.internal:3306/adventure
        username: admin
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
      data:
        redis:
          host: host.minikube.internal
          port: 6379
          password: superpassword  # Add the password here
    app:
      config:
        kafka:
          server: host.minikube.internal:29092
          topic: report-message
          partitions: 1
          

  mytestfile.txt: |+
    hello my friend
    
