apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventureshops-deployment
  namespace: dev
  labels:
    app: adventureshops-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventureshops-deployment
  template:
    metadata:
      labels:
        app: adventureshops-deployment
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - localhost
      containers:
      - name: adventureshops-deployment
        image: ion20155/adventureshops:1.0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /adventureshops/health/check
            port: http
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /adventureshops/health/check
            port: http
          failureThreshold: 3
          periodSeconds: 30
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx1024m"
        - name: SPRING_CONFIG
          value: "--spring.config.location=/home/app/config/application.yaml"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://host.minikube.internal:3306/adventure
        volumeMounts:
        - name: adventureshops-volume
          subPath: application2.yaml
          mountPath: /home/app/config/application.yaml
        - name: adventureshops-volume
          subPath: mytestfile.txt
          mountPath: /home/app/config/mytestfile.txt
      volumes:
      - name: adventureshops-volume
        configMap:
          name: adventureshops-configmap

