apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-configmap
  namespace: dev
data:
  application-2.yaml: |+
    spring:
      application:
        name: adventureshops
      servlet:
        context-path: /api/v1
      datasource:
        url: jdbc:mysql://localhost:3306/adventure
        username: admin
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
        ddl-auto: update
      data:
        redis:
          host: localhost
          port: 6379
      kafka:
        bootstrap-servers: localhost:9092
        consumer:
          group-id: adventureshops-consumer-group


  mytestfile.txt: |+
    hello my friend
    
