FROM maven:3.8.3-openjdk-17 AS build
LABEL authors="thebi"

RUN mkdir /home/app
WORKDIR /home/app

COPY ./pom.xml ./pom.xml
RUN mvn dependency:resolve

COPY ./src ./src
RUN mvn clean package


###BUILD IMAGE
FROM openjdk:17

COPY --from=build target/*0.0.1-SNAPSHOT.jar /home/app/app.jar

WORKDIR /home/app

ENTRYPOINT exec java -jar /home/app/app.jar

