@startuml
title getPlayerById(id: Integer)

actor User as u
boundary API as a
database Database as d

u->a : GET /api/v1/player/{id}
a->d: findById(player_id)
    d-->a : player
a->a : Validate player

alt Player found

    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Player data
else Player not found
    a->u : 404 Not Found
    a->u : "Player not found"
end

@enduml
