@startuml
title attackMonster(playerId: Integer, monsterId: Integer)

actor User as u
boundary API as a
database Database as d

u->a : POST /api/v1/monster/attack(playerId, monsterId)

a->d : Find player by playerId
a->d : Find monster by monsterId
d-->a : Receive Player and Monster's data
a->a : Validate Player and Monster

alt Player and monster found
    a->d : Find player's damage by level
    d-->a : Receive player's damage
    a->a : Calculate player's damage
    a->a : Check if monster's health is less than or equal to player's damage
    alt Monster killed
        a->d : Add monster's drop item to player's inventory
        ...200 OK...
        a->u : "You have successfully killed the monster. You have received a drop item."
    else Monster not killed
        a->u : 200 OK
        a->u : "You have been killed by the monster. Your damage is not enough."
    end
else Player or monster not found
    a->u : 404 Not Found
    a->u : "Player or monster not found."
end

@enduml
