@startuml
title buyItem(playerId: Integer, itemId: Integer)

actor User as u
boundary API as a
database Database as d

u->a : POST /api/v1/market/buy(playerId, itemId)
a->d : Find market item by itemId
d-->a : Receive Item data
a->a : Validate Item
alt Market item not found
    a->u : 400 Bad Request
    a->u : "Market item not found with ID: itemId"
else Market item found
    a->d : Find player by playerId
    d-->a : Receive player data
    a->a : Validate player
    alt Player not found
        a->u : 400 Bad Request
        a->u : "Player not found with ID: playerId"
    else Player found
        a->d : Find inventory by market item's inventory ID
        d-->a : Receive inventory data
        a->a : Validate inventory
        alt Inventory not found
            a->u : 400 Bad Request
            a->u : "Inventory item not found with ID: inventoryId"
        else Inventory found
            a->d : Find account by player's account ID
            d-->a : Receive account data
            a->a : Validate account
            alt Account not found
                a->u : 400 Bad Request
                a->u : "Account not found for player with ID: playerId"

            else Account found
                a->a : Check if player owns the inventory
                alt Player does not own the inventory
                    a->u : 400 Bad Request
                    a->u : "You are not authorized to purchase this item."
                else Player owns the inventory
                    a->a : Check if market item is sold
                    alt Market item is sold
                        a->u : 400 Bad Request
                        a->u : "The item has already been sold."
                    else Market item is not sold
                        a->a : Check if player has enough balance
                        alt Player does not have enough balance
                            a->u : 400 Bad Request
                            a->u : "Your balance is insufficient."
                        else Player has enough balance
                            a->d : Deposit cost to seller's account
                            a->d : Withdraw cost from buyer's account
                            a->d : Change inventory owner to buyer
                            a->d : Save market item
                            a->d : send notification to seller's inbox
                            a->u : 200 "Successfully purchased an item."
          note right
            the <U+0025>autonumber<U+0025> works everywhere.
            Here, its value is ** %autonumber% **
          end note
                            a->u : JSON Inventory data
                        end
                    end
                end
            end
        end
    end
end

@enduml
