@startuml
title getAllMarketPlace()

actor User as u
boundary API as a
database Database as d

u->a : GET /api/v1/market
a->d: findAll()
    d-->a : marketplaces data
a->a : Validate markets

alt Market found

    a->u : 200 OK
    a->u : "Data retrieved successfully"
    a->u : JSON Market data
else Market not found
    a->u : 404 Not Found
    a->u : "Market not found"
end

@enduml
